## 3. 넘파이
넘파이란? 다차원배열과 수학 함수를 제공하는 모듈(라이브러리)  
모듈이란? 필요한 기능을 미리 만들어두고 가져다 쓰는것

3.1 ndarry  
다차원 배열  
다차원 배열의 특징:  
1. 리스트와 비교했을때 계산 속도가 빠름
2. 리스트와 달리 모든 요소의 타입이 같음

In [166]:
# 먼저 numpy 모듈 가져오기
# 외부에 있는 모듈 파일을 가지고 올때는 import  
# 모듈의 이름이 길때는 별칭 붙이기 as np
import numpy as np

In [167]:
# 넘파이 배열 만들기  
# 입력값: 리스트
# 결과: 넘파이 배열
a = np.array([1,2,3])
a
b = np.array(['a','b','c'])
b

array(['a', 'b', 'c'], dtype='<U1')

2차원 배열 생성  

In [168]:
# 2차원 배열 생성  
# 2차원 배열은 1차원 배열의 묶음
c = np.array([[1,2,3],[4,5,6]])
c
# 3행 3열 크기의 2차원 배열 생성
d = np.array([[1,2,3],[4,5,6], [7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
# 주석 단축키 : ctrl + /
# arrange : 숫자 여러개를 생성하는 함수
# 연속된 숫자 10개를 생성
# 개수만 넣으면 0부터 시작됨
a = np.arange(10)
# 1부터 10까지 생성
# 범위(시작, 끝)
b = np.arange(1,10)
# 1부터 10까지 2씩 건너뛰면서 생성
c = np.arange(1,11,2)
c

array([1, 3, 5, 7, 9])

## 연습문제1

In [170]:
# 문제 1
# 파이썬 리스트 scores = [85, 90, 78, 92, 88]를 넘파이 배열로 변환하여 출력하세요
arr_scores = np.array([85, 90, 78, 92, 88])
print(arr_scores)

# 문제 2
# 리스트 heights = [160, 165, 170, 175, 180] 를 넘파이 배열로 변환하여 출력하세요
arr_heights = np.array([160, 165, 170, 175, 180])
print(arr_heights)

# 문제 3
# 리스트 prices = [1200, 1500, 1800, 2100] 넘파이 배열로 변환하여 출력하세요
arr_prices = np.array([1200, 1500, 1800, 2100])
print(arr_prices)

# 문제 4
# 리스트 temps = [20, 22, 19, 25, 30] 넘파이 배열로 변환하여 출력하세요
arr_temps = np.array([20, 22, 19, 25, 30])
print(arr_temps)

[85 90 78 92 88]
[160 165 170 175 180]
[1200 1500 1800 2100]
[20 22 19 25 30]


In [171]:
# 문제 1
# 0부터 4까지 숫자를 원소로 가지는 배열을 생성하세요.
# arange는 파이선의 range 함수와 비슷
# arange의 반환값: 배열
arr1 = np.arange(5)
print(arr1)

# 문제 2
# 0부터 9까지 숫자를 원소로 가지는 배열을 생성하세요.
arr2 = np.arange(10)
print(arr2)

# 문제 3
# 3부터 7까지 숫자를 원소로 가지는 배열을 생성하세요.
arr3 = np.arange(3, 8)
print(arr3)

# 문제 4
# -2부터 2까지 숫자를 원소로 가지는 배열을 생성하세요.
arr4 = np.arange(-2, 3)
print(arr4)

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[-2 -1  0  1  2]


## 예제

In [172]:
# zeros : 배렬을 생성하고 값을 0으로 초기화
# 10개 크기의 배열 생성
np.zeros(10)
# 2차원 배열 생성
np.zeros((3,3)) # 행 열

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [173]:
# 3개 크기의 1차원 정수 배열 생성
# 파이썬의 리스트와 달리

# 1차원 배열 생성
a = np.array([1,2,3])
# 배열의 정보를 확인
print(a.dtype) # 자료형
print(a.ndim) # 배열의 차원
print(a.shape) # 행열 크기

int64
1
(3,)


In [174]:
# 2행 3열의 2차원 배열 생성
# 행열?
b = np.array([[1,2,3], [4,5,6]])
print(b.dtype)
print(b.ndim)
print(b.shape)

int64
2
(2, 3)


In [175]:
# 실수형 1차원 배열 생성
arr = np.array([1.1, 2.1, 3.1])
# 자료형확인
arr.dtype
# 배열의 형변환
# float -> int
arr2 = arr.astype(np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [176]:
# 파이썬의 리스트 생성
lis = [1,2,3]
# 파이썬의 각 원소에 3씩 더하기
# 리스트의 원소에 하나씩 계산하려면 for 반복문을 사용
for i in lis:
    print(i + 3)

4
5
6


In [177]:
# 넘파이 배열 생성
# 넘파이 배열은 for문 없이 각 우너소에 값을 계산할 수 있다!
# 넘파이 배열을 자동으로 각 원소에 반복 수행이 된다
a = np.array([1,2,3])
# 각 원소에 3씩 더하기
a + 3

array([4, 5, 6])

In [178]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# 배열 두개를 비교
a > b

array([False, False, False])

인덱스와 슬라이스

In [179]:
# 1차원 배열 생성
# 0~9 숫자 만들고 1차원 배열 생성
a = np.arange(10)
print(a)
# 배열의 원소 하나 꺼내기
a[1]
# 번위로 값 꺼내기 (슬라이스)
a[3:6]
# 원소 값 변경하기
# 두번쨰 원소의 값 변경하기
a[1] = 99
a
# 특정 범위에 있는 값을 모두 변경하기
# 3,4,5 번째 데이터 변경
a[3:6] = 88
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0, 99,  2, 88, 88, 88,  6,  7,  8,  9])

In [180]:
# 배열 전체 선택
# a를 출력하는 것과 같다
a[:]

array([ 0, 99,  2, 88, 88, 88,  6,  7,  8,  9])

## 연습문제 2

In [181]:
arr = np.array([10, 20, 30, 40, 50])

# 배열의 첫 번째 값을 꺼내서 출력하세요 # 결과: 10
print(arr[0])
# 배열의 세 번째 값을 꺼내서 출력하세요 # 결과: 30
print(arr[2])
# 배열의 마지막 값을 꺼내서 출력하세요 # 결과: 50
print(arr[-1])

# 배열의 두번째 값을 200으로 바꾸세요
arr[1] = 200
print(arr)
# 결과: [10 200 30 40 50]

# 배열의 네 번째 값을 999로 바꾸세요
arr[3] = 999
print(arr)
# 결과: [10 200 30 999 50]

10
30
50
[ 10 200  30  40  50]
[ 10 200  30 999  50]


In [182]:
arr = np.array(['가','나','다','라','마'])

# 배열의 두 번째 값을 꺼내서 출력하세요 # 결과: 나
print(arr[1])
# 배열의 네 번째 값을 꺼내서 출력하세요 # 결과: 라
print(arr[3])
# 배열의 마지막 값을 꺼내서 출력하세요 # 결과: 마
print(arr[-1])

# 배열의 첫번째 값을 '하'로 바꾸세요
# 결과: ['하','나','다','라','마']
arr[0] = '하'
print(arr)

# 배열의 세번째 값을 '호'로 바꾸세요
# 결과: ['하','나','호','라','마']
arr[2] = '호'
print(arr)

나
라
마
['하' '나' '다' '라' '마']
['하' '나' '호' '라' '마']


In [183]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# 배열의 처음 3개 값을 꺼내서 출력하세요
# 결과 : [10 20 30]
print(arr[:3])
# 배열의 네 번쨰부터 끝까지 값을 꺼내서 출력하세요
# 결과: [40 50 60 70]
print(arr[3:])
# 배열의 두 번째부터 다섯 번째까지 값을 꺼내서 출력하세요
# 결과: [20 30 40 50]
print(arr[1:5])

[10 20 30]
[40 50 60 70]
[20 30 40 50]


In [184]:
arr = np.array(['a','b','c','d','e','f','g'])

# 배열의 처음 3개 값을 꺼내서 출력하세요
# 결과 : ['a' 'b' 'c']
print(arr[:3])
# 배열의 네 번쨰부터 끝까지 값을 꺼내서 출력하세요
# 결과: ['d' 'e' 'f' 'g']
print(arr[3:])
# 배열의 두 번째부터 다섯 번째까지 값을 꺼내서 출력하세요
# 결과: ['b' 'c' 'd' 'e']
print(arr[1:5])

['a' 'b' 'c']
['d' 'e' 'f' 'g']
['b' 'c' 'd' 'e']


## 2차원 배열의 인덱싱

In [185]:
# 3행 3열 2차원 배열 생성
arr = np.array([[1,2,3], [4,5,6,], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [186]:
# 2차원 배열의 인덱스
# 행(인덱스)
# 열(컬럼)
# 첫번째 행 꺼내기
arr[0]

array([1, 2, 3])

In [187]:
# 1 꺼내기
arr[0][0]
# 9 꺼내기
arr[2][2]
# 5 꺼내기
arr[1][1]
arr[1,1]

np.int64(5)

In [188]:
# 배열 원소의 값 바꾸기
# 0 -> 1
arr[0][0] = 0
arr
# 5 -> 0
arr[1][1]= 0
arr

array([[0, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

## 2차원 배열 슬라이스

In [189]:
arr = np.array([[1,2,3], [4,5,6,], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [190]:
# 행을 기준으로 슬라이스
# 처음부터 두번째 행까지
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
# 행: 1번 2번
# 열: 1번 2번
arr[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [192]:
# 행: 0번 1번
# 열: 0번 1번
arr[ :2, :2]

array([[1, 2],
       [4, 5]])

In [193]:
# 행: 슬라이스x
# 열: 0 1 번
arr[ 1, 0:2 ]

array([4, 5])

In [194]:
## 연습문제
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# 첫 번째 행의 두 번째 값을 꺼내서 출력하세요. 결과 : 20
print(arr[0, 1])
# 세 번째 행의 첫 번째 값을 꺼내서 출력하세요. 결과 : 70
print(arr[2, 0])
# 두 번째 행 전체를 꺼내서 출력하세요. 결과: [40 50 60]
print(arr[1])
# 두 번째 열 전체를 꺼내서 출력하세요. 결과: [20 50 80]
print(arr[ : ,1])
# 첫 번째 행의 세 번째 값을 300으로 변경
# [[10 20 300]
#     [40 50 60]
#     [70 80 90]]
arr[0, 2] = 300
print(arr)




20
70
[40 50 60]
[20 50 80]
[[ 10  20 300]
 [ 40  50  60]
 [ 70  80  90]]


In [195]:
## 연습문제
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# 두 번째 행의 세 번째 값을 꺼내서 출력하세요. 결과 : 7
print(arr[1, 2])
# 네 번째 행의 첫 번째 값을 꺼내서 출력하세요. 결과 : 13
print(arr[3, 0])
# 세 번째 행 전체를 꺼내서 출력하세요. 결과: [9 10 11 12]
print(arr[2])
# 네 번째 열 전체를 꺼내서 출력하세요. 결과: [4 8 12 16]
print(arr[:, 3])
# 첫 번째 행의 네 번째 값을 100으로 변경
# [1, 2, 3, 100]
arr[0, 3] = 100
print(arr)


7
13
[ 9 10 11 12]
[ 4  8 12 16]
[[  1   2   3 100]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]]


In [196]:
## 연습문제
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# 첫 번째 행의 앞 2개 숫자를 꺼내서 출력. 결과: [10 20]
print(arr[0][0:2])
# 두 번째 행부터 세번째 행까지 전체를 꺼내서 출력.
# [[40 50 60]
#  [70 80 90]]
print(arr[1:3])
#모든 행에서 두번쨰와 세번째 열만 꺼내서 출력.
# [[20 30]
#  [50 60]
#  [80 90]]
print(arr[ : ,1:3])

[10 20]
[[40 50 60]
 [70 80 90]]
[[20 30]
 [50 60]
 [80 90]]


## 불리언 인덱스
인덱스란? 데이터의 위치

In [197]:
# 학생 배열 생성
students = np.array(['철수', '영희', '민수', '철수', '철수'])
# 학생들의 대출 이력(책제목, 대출일)
books = np.array([
    ['수학의 정석',7], ['해리포터',10], ['파이썬 입문',5], ['한국사',5], ['데미안',12]
])

In [198]:
# 여기서 철수의 대출 이력만 조회하기
# 배열 == '비교값'
# 배열 전체에 함수를 비교ㄹ
# 총 5번 비교하고 bool 배열 반환
arr = (students == '철수')
arr

array([ True, False, False,  True,  True])

In [199]:
# books 배열의 인덱스에 bool 배열 넣기
# true에 해당하는 원소만 반환
# 조건에 맞는 원소를 꺼낼때 사용
books[students == '철수']

array([['수학의 정석', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [201]:
print(students != '철수')
# 철수가 아닌 대출 이력 찾기
# true에 해당하는 원소만 반환
books[ students != '철수' ]

[False  True  True False False]


array([['해리포터', '10'],
       ['파이썬 입문', '5']], dtype='<U21')

In [206]:
# '수학의 정석'을 찾아서 제목을 '자바의 정석'으로 바꾸기
books == '수학의 정석'
# bool 배열로 원소를 찾고 값 교체
books[books == '수학의 정석'] = '자바의 정석'
books

array([['자바의 정석', '7'],
       ['해리포터', '10'],
       ['파이썬 입문', '5'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [209]:
# 대출 이력 중에서 철수가 아닌 항목을 찾고
# 행 전체를 7로 바꾸기
students != '철수'

books[students != '철수'] = 7
books

array([['자바의 정석', '7'],
       ['7', '7'],
       ['7', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [249]:
# 연습문제
arr = np.array([10,20,30,40,50,60,70])

In [250]:

# 배열에서 30보다 큰 값만 꺼내서 출력
arr > 30
arr[arr > 30]
print(arr)

[10 20 30 40 50 60 70]


In [251]:
# 배열에서 짝수 값만 꺼내서 출력
arr[arr%2==0]
print(arr)

[10 20 30 40 50 60 70]


In [252]:
# 배열에서 50보다 큰 값을 모두 999로 변경
arr[arr == 50]
arr[arr > 50] = 999
print(arr)


[ 10  20  30  40  50 999 999]


연습문제 2

In [264]:
# 직원 이름 배열
employees = np.array(['짱구', '철수', '유리', '맹구', '훈이'])
# 직원별 월급(만원단위)
salaries = np.array([250, 320, 280, 400, 150])
# 직원 이름과 월급은 대응

# 맹구의 급여를 조회
employees == '맹구'
a = salaries[employees == '맹구']
print(a)

# 급여가 300만원 이상인 직원들의 이름 출력
b = employees[salaries >= 300]
print(b)
# 급여가 200만원 미만인 직원들 급여를 모두 200으로 올리기
salaries[salaries < 200] = 200
salaries

print(salaries)


[400]
['철수' '맹구']
[250 320 280 400 200]


## 3.2 배열의 모양 바꾸기

In [267]:
# 1~9 숫자가 담긴 1차원 배열 생성
# reshape : 배열의 형태를 바꾸는 함수
# 1차원 -> 2차원
# ㄱ행 3열 크기의 배열로 변환
print(np.arange(1,10))
arr = np.arange(1,10).reshape(3,3)
arr
# 

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [269]:
# 1~16 숫자가 담긴 1차원 배열
print(np.arange(1,17))
a = np.arange(1,17).reshape(4,4)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [270]:
# 1~12 1차원 배열
# 이배열을 3행 4열 배열로 변환
a = np.arange(1,13).reshape(3,4)
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [284]:
# 연습문제
# 0부터 11까지 숫자를 생성한 뒤, 3행 4열 배열로 바꾸세요
a = np.arange(12).reshape(3, 4)
print(a)
# 1부터 16까지 숫자를 생성한 뒤, 4행 4열 배열로 바꾸세요
b = np.arange(1,17).reshape(4, 4)
print(b)
# 1부터 20까지 숫자를 생성한 뒤, 5행 4열 배열로 바꾸세요
c = np.arange(1,21).reshape(5, 4)
print(c)
# 10부터 25까지 숫자를 생성한 뒤, 4행 4열 배열로 바꾸세요
d = np.arange(10,26).reshape(4, 4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


## 3.3 난수를 생성하는 방법
난수란? 랜덤값

In [291]:
# 랜덤값 만들기
# 표준 정규 분포 : 표준 편차가 1인 그래프에서 랜덤값을 생성( -3 ~ 3 )
arr = np.random.standard_normal(size = 10)
arr

array([ 0.64108205, -0.43633616, -0.70147928,  0.02551041,  1.20058196,
        1.09608286,  0.15743597, -0.05167588, -0.12354148, -0.43050565])

In [293]:
# 균일 분포 : 범위 0~1. 모든 값이 같은 확률로 나옴
arr = np.random.uniform(size=10)
arr

array([0.41089298, 0.18109405, 0.83824421, 0.11114048, 0.0250164 ,
       0.86210344, 0.04616699, 0.08289477, 0.2825825 , 0.47833522])

In [295]:
# 연습문제
# 표준정규분포에서 랜덤값 5개를 생성
a = np.random.standard_normal(size=5)
print(a)
# 균일분포에서 랜덤값 5개를 생성
b = np.random.uniform(size=5)
print(b)

[-0.30823756 -1.07580705  1.83706651 -1.36104737 -1.06818076]
[0.30589409 0.12444843 0.3675994  0.86810337 0.12704088]


## 3.4 유니버설 함수
반복문 없이 배열 전체에 계산을 해주는 함수

In [296]:
# 0 ~ 9 숫자가 담긴 1차원 배열 생성
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [298]:
# 파이썬의 리스트는 for문을 사용해서 계산해야함
# 넘파이의 배열은 for문 없이 계산 가능
# 배여 전체에 3 더하기
# add : 더하기
np.add(arr, 3)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [303]:
a = np.array([1,7,2,4,10])
b = np.array([3,4,5,6,7])

# 두 배열을 비교하여 더 큰값 저장하기
np.maximum(a, b)

array([ 3,  7,  5,  6, 10])

조건문

In [313]:
# 배열 두개 만들기
a = np.array([1,2,3])
b = np.array([10,20,30])
# 불리언 배열 만들기
cond = np.array([True, True, False])

In [305]:
# where(조건, 참일때값, 거짓일때값) : 조건문 쓰기
# 조건이 참이면 a에서 값을 선택, 거짓이면 b에서 값을 선택
# where는 삼항연산자와 비슷
result = np.where(cond, a, b)
result

array([ 1,  2, 30])

In [308]:
# 1차원 배열 생성
arr = np.array([-2, -1, 0, 1, 2])

# 양수면 'o', 음수면 'x'로 반환
# 조건, 참일때값, 거짓일때 값
# 조건이 true면 o를 선택, false면 x를 선택
np.where(arr > 0, 'o', 'x')

array(['x', 'x', 'x', 'o', 'o'], dtype='<U1')

In [317]:
# 연습문제

# 배열 [5, 12, 7, 20, 3]에서 10보다 크면 '100', 10 이하면 '0'으로 바꾸세요
arr = np.array([5, 12, 7, 20, 3])
print(np.where( arr > 10, 100, 0))

# 배열 [15, 8, 22, 6, 13]에서 짝수면 '1', 홀수면 '-1'으로 바꾸세요
bb = np.array([15, 8, 22, 6, 13])
print(np.where( bb % 2 == 0, 1, -1))

# 배열 [10,20,30,40,50]과 [1,2,3,4,5]를 만들고 
# 조건 배열[True, False, True, False, True]를 사용해
# 조건 True일 때는 첫 번째 배열 값, False일 떄는 두번째 배열 값을 선택하세요
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])
cond = np.array([True, False, True, False, True])
result = np.where(cond, arr1, arr2)
result

[  0 100   0 100   0]
[-1  1  1  1 -1]


array([10,  2, 30,  4, 50])

통계를 구할 때 자주 사용하는 함수들  
(최대 최소 합계 평균)

In [324]:
# 파이썬의 리스트 생성
lis = [1,2,3,4,5]
# 리스트의 총합을 구하세요
sum = 0
for i in lis:
    sum = sum + 1
print(sum)
# 리스트의 평균을 구하세요
print(sum/len(lis))

5
1.0


In [325]:
# 이번에는 넘파이 배열로 합계와 평균 구하기
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
# 배열에서 제일 큰 값
print(np.max(arr))
# 배열에서 제일 작은 값
print(np.min(arr))

15
3.0
5
1


In [332]:
# 아래는 하루 동안 먹은 음식들의 칼로리다
# 김밥 250
# 라면 550
# 떡볶이 400
# 치킨 800
kcal = [250, 550, 400, 800]

# 하루 먹은 음식의 총 칼로리는 몇인가?
ksum = np.sum(kcal)
print(ksum)
# 음식 4개의 평균 칼로리는 몇인가?
avg = np.mean(kcal)
print(avg)
# 칼로리가 가장 높은 음식은 몇 칼로리인가?
print(np.max(kcal))
# 칼로리가 가장 낮은 음식은 몇 칼로리인가?
print(np.min(kcal))

2000
500.0
800
250


In [337]:
# 아래는 일주일 동안 운동한 시간(분)이다.
# • 월: 30
# • 화: 45
# • 수: 60
# • 목: 20
# • 금: 40
# • 토: 50
# • 일: 35

m = [30, 45, 60, 20, 40, 50, 35]

# 일주일 동안 총 운동 시간은 몇 분인가?
total = np.sum(m)
print(total)
# 하루 평균 운동 시간은 몇 분인가?
np.mean(m)
# 가장 오래 운동한 날은 몇 분인가?
np.max(m)
# 가장 짧게 운동한 날은 몇 분인가?
np.min(m)

280


np.int64(20)

## 행/열 단위로 합계 구하기

In [347]:
arr = np.arange(1, 10).reshape(3,3)
print(arr)

# 배열의 합계 구하기
arr.sum()
# 2 차원 배열에서 행 또는 열 방향으로 합 구하기
# axis -> 방향, 0은 세로, 1은 가로 / 2차원 이상에서만 사용
arr.sum(axis=0)
arr.sum(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [353]:
# 누적값 구하기
# 합을 구하는 중간 과정을 보여줌
arr = np.array([1,2,3,4,5])
arr.cumsum()

array([ 1,  3,  6, 10, 15])

In [359]:
# 2차원 배열 생성
arr = np.array([ [0,1,2],[3,4,5], [6,7,8] ])
print(arr)
# 2차원 배열의 누적값 구하기
# 기준 설정(세로방향. 위->아래)
# 앞에 있는 수를 더한 결과
# print(arr.cumsum(axis = 0))
# 가로 방향(왼->오)
print(arr.cumsum(axis = 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
